### ISSUE TITLE
ctrl + delete / backspace doesn't delete words

### ISSUE THREAD

**Issue by JJSax** [xhighway999/luapad#1]
I would expect these actions to delete an entire word at a time. 

Currently ctrl blocks both delete and backspace from working at all. 

Luapad v0.5.2
Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by xhighway999** [comment]
Thank you !
I've added an experimental word-delete shortcut (both CTRL + DELETE and CTRL + BACKSPACE work)
