### ISSUE TITLE
Ctrl + s freezes the webpage

### ISSUE THREAD

**Issue by JJSax** [xhighway999/luapad#2]
What Happens.
This key combo will make it so you can't click anything, or even copy your work to refresh the page.  None of the buttons work, even the hyperlinks to github.

What I would expect to happen.
Most websites bring up the windows save as screen, some may use that to save your document. 

Luapad version 0.5.2
Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by xhighway999** [comment]
Hi, 
thank you for reporting this issue. I've fixed this problem as of LuaPad v0.6.1.
